image: "wiremock/wiremock"
applicationPort: 8080
imagePullPolicy: Always
replicas: 2
useInterpodAntiAffinity: true
ingressHost: "{{.Release.Name}}.service.core-compute-preview.internal"
additionalIngressHosts: ["ci-01.{{.Values.global.environment}}.platform.hmcts.net"]
configmap:
  VAR_A: VALUE_A
  VAR_B: VALUE_B
secrets:
  CONNECTION_STRING:
    secretRef: some-secret-reference
    key: connectionString
    disabled: true
prometheus:
  enabled: true
keyVaults:
  "plumsi":
    excludeEnvironmentSuffix: false
    secrets:
      - test-secret
global:
  tenantId: "531ff96d-0ae9-462a-8d2d-bec7c0b42082"
  environment: aat
  enableKeyVaults: true