apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "hmcts.wiremock.releaseName" . }}-chart-wiremock
data:
  liveness-mock.json: |
    {
      "request": {
        "method": "GET",
        "url": "/health/liveness"
      },
      "response": {
        "status": 200
      }
    }
  liveness-mock-2.json: |
    {
      "request": {
        "method": "GET",
        "url": "/health"
      },
      "response": {
        "status": 200
      }
    }  
  readiness-mock.json: |
    {
      "request": {
        "method": "GET",
        "url": "/health/readiness"
      },
      "response": {
        "status": 200
      }
    }

