apiVersion: v2
description: A Helm chart for wiremock
name: wiremock
# This is the chart version. This doesn't need to be incremented on every change.
# It is managed by release pipeline based on Github tag
version: 1.0.0 # Do not change
appVersion: 3.3.9 # Do not change
type: application


dependencies:
  - name: library
    version: 2.2.2
    repository: https://hmctspublic.azurecr.io/helm/v1/repo/
